docker_kernel_min_version: '2.6.32-431'

# versioning: docker-io itself is pinned at docker 1.5

docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: docker-io

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
